---
#
- name: Upgrade pip
  ansible.builtin.pip:
    name: "{{ venv_default_software }}"
    extra_args: --upgrade
    virtualenv: "{{ venv_home_dir }}"
    virtualenv_command: python3 -m venv
    state: forcereinstall

- name: Install virtualenv software
  ansible.builtin.pip:
    name: "{{ venv_software }}"
    virtualenv: "{{ venv_home_dir }}"
    virtualenv_command: python3 -m venv
